### ISSUE TITLE
Task 1 - Defend reentrancy attack

### ISSUE THREAD

**Issue by diceyecid** [Siriussee/reentrancy-attack#1]
The Issue feature is disable on [Siriussee/underflow-attack](https://github.com/Siriussee/underflow-attack). I guess here is where I should raise the issue for bonus task...

---

# Task 1 - Defend reentrancy attack

Please refer to the source code on GitHub: [diceyecid/reentrancy-attack](https://github.com/diceyecid/reentrancy-attack).

1. **Secured Vault Contract**: The secured vault contract is located at `contracts/FixedEtherVault.sol`.

2. **Attack Script**: The script attempting the reentrancy attack can be found at `scripts/attack.full.ts`.

3. **Defense Mechanism**:

    To defend against the reentrancy attack, the following modifications have been implemented in the secured vault contract:

    - A require gate has been added to verify if the user's balance is positive before proceeding with the send Ether operation.

    - The code to update the user's balance is moved to execute before calling send Ether operation.

    These changes ensure that the user's balance is updated prior to sending Ethers, and the require gate prevents the execution of the withdraw function if the user's balance is not positive.

**Comment by Siriussee** [comment]
Correct defence. I will get back to the scripts later.

**Comment by ZeeChono** [comment]
Hi,
I met a problem when trying to run your fixed_vault solution. So basically I run over:
deploy.ts
deploy.attack.ts
query.ts
attack.full.ts

Then I got the following output in the screenshot:
<img width="1056" alt="image" src="https://github.com/Siriussee/reentrancy-attack/assets/54852475/9858652f-2345-4613-a916-b4cd59b2ccbf">
As you can see, it is complaining "Failed to send Ether" instead of the guard message "Insufficient balance". If the guard gate is working, shouldn't we see the "Insufficient balance" in the console?
I am wondering what is the code execution flow in this case. 

Thank you!

**Comment by diceyecid** [comment]
@ZeeChono Your execution sequence is correct.

I think this happened because of the function call stack. Here is what I think is happening:

1. `attack()` is initiated by the attacker.
2. During the execution of `attack()`, it calls `withdraw()`.
3. Within the execution of `withdraw()`, the require condition for a balance above zero is passed and the send Ether operation is performed.
4. The `fallback()` function is triggered as a result of receiving Ether.
5. Within the execution of `fallback()`, it calls `withdraw()` once again.
6.  In the second execution of `withdraw()`, the require condition for a balance above zero fails, leading to an exception with the message: "Insufficient balance".
7. The exception is caught by the parent function, `fallback()`, causing it to propagate up the call stack.
8. The first `withdraw()` receives the "Insufficient balance" exception, resulting in the `success` variable being set to `false`. This causes another exception with the message: "Failed to send Ether".
9. Finally, the first function in the call stack, `attack()`, receives the "Failed to send Ether" error, leading to the exception being thrown and logged to the console.

Here is what I envision the call stack looks like in each stage:

| stage | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |
|---|---|---|---|---|---|---|---|---|---|
| Call Stack | <br><br><br>`attack()` | <br><br>`withdraw()`<br>`attack()` | <br><br>`withdraw()`<br>`attack()` | <br>`fallback()`<br>`withdraw()`<br>`attack()` | `withdraw()`<br>`fallback()`<br>`withdraw()`<br>`attack()` | `withdraw()`<br>`fallback()`<br>`withdraw()`<br>`attack()` | <br>`fallback()`<br>`withdraw()`<br>`attack()` | <br><br>`withdraw()`<br>`attack()` | <br><br><br>`attack()` |


_* Please note that `attack()` belongs to `Attack.sol`, `withdraw()` and `fallback()` belong to `FixedEtherVault.sol`_

---

To address the issue, I have updated the repo to incorporate some `try/catch` statements and console logs into the code. In the running Hardhat node, you will be able to observe that the "Insufficient balance" exception is initially thrown but gets overridden by the "Failed to send Ether" exception towards the end.

![try_catch_snippit](https://github.com/Siriussee/reentrancy-attack/assets/49296963/a6ebcd7d-ef5b-4b76-bcbc-c4a570120d82)

![hardhat_node_console](https://github.com/Siriussee/reentrancy-attack/assets/49296963/7a5705cd-6136-4138-b433-d8219eb41c39)

**Comment by ZeeChono** [comment]
@diceyecid 
The call stack is really helpful for understanding.
Thanks for sharing!

**Comment by Siriussee** [comment]
@diceyecid Hi, please send me an email and include your name and student id in the email. The extra points will be reflected in your midterm. You can find my email over the course outline on Canvas. Thanks.
